anytask/courses/urls.py
from django.conf.urls import url
from courses.pythontask import get_task, cancel_task
import courses.views

urlpatterns = [
    url(r'^(?P<course_id>\d+)$', courses.views.course_page, name="courses.views.course_page"),
    url(r'^(?P<course_id>\d+)/seminar/(?P<task_id>\d+)$',
        courses.views.seminar_page, name="courses.views.seminar_page"),
    url(r'^(?P<course_id>\d+)/queue$', courses.views.queue_page, name="courses.views.queue_page"),
    url(r'^(?P<course_id>\d+)/gradebook/$', courses.views.gradebook, name="courses.views.gradebook"),
    url(r'^(?P<course_id>\d+)/gradebook/seminar/(?P<task_id>\d+)/$',
        courses.views.gradebook, name="courses.views.gradebook"),
    url(r'^(?P<course_id>\d+)/gradebook/group/(?P<group_id>\d+)/$',
        courses.views.gradebook, name="courses.views.gradebook"),
    url(r'^(?P<course_id>\d+)/gradebook/seminar/(?P<task_id>\d+)/group/(?P<group_id>\d+)$',
        courses.views.gradebook, name="courses.views.gradebook"),
    url(r'^year/(?P<year>\d+)', courses.views.courses_list, name="courses.views.courses_list"),
    url(r'^edit_course_information', courses.views.edit_course_information,
        name="courses.views.edit_course_information"),
    url(r'^set_spectial_course_attend', courses.views.set_spectial_course_attend,
        name="courses.views.set_spectial_course_attend"),
    url(r'^(?P<course_id>\d+)/settings$', courses.views.course_settings, name="courses.views.course_settings"),
    url(r'^change_visibility_hidden_tasks$', courses.views.change_visibility_hidden_tasks,
        name="courses.views.change_visibility_hidden_tasks"),
    url(r'^change_visibility_academ_users$', courses.views.change_visibility_academ_users,
        name="courses.views.change_visibility_academ_users"),
    url(r'^set_course_mark$', courses.views.set_course_mark, name="courses.views.set_course_mark"),
    url(r'^set_task_mark$', courses.views.set_task_mark, name="courses.views.set_task_mark"),
    url(r'^change_table_tasks_pos', courses.views.change_table_tasks_pos, name="courses.views.change_table_tasks_pos"),
    url(r'^ajax_update_contest_tasks/$', courses.views.ajax_update_contest_tasks,
        name="courses.views.ajax_update_contest_tasks"),
    url(r'^ajax_rejudge_contest_tasks/$', courses.views.ajax_rejudge_contest_tasks,
        name="courses.views.ajax_rejudge_contest_tasks"),
    url(r'^pythontask/get_task/(?P<course_id>\d+)/(?P<task_id>\d+)$', get_task,
        name="courses.pythontask.get_task"),
    url(r'^pythontask/cancel_task/(?P<course_id>\d+)/(?P<task_id>\d+)$', cancel_task,
        name="courses.pythontask.cancel_task"),
    url(r'^(?P<course_id>\d+)/attendance$', courses.views.attendance_page, name="courses.views.attendance_page"),
    url(r'^(?P<course_id>\d+)/attendance/group/(?P<group_id>\d+)/$', courses.views.attendance_page,
        name="courses.views.attendance_page"),
    url(r'^lesson_visited$', courses.views.lesson_visited, name="courses.views.lesson_visited"),
    url(r'^lesson_delete$', courses.views.lesson_delete, name="courses.views.lesson_delete"),
    url(r'^(?P<course_id>\d+)/statistic$', courses.views.view_statistic, name="courses.views.view_statistic"),
    url(r'^ajax_get_queue$', courses.views.ajax_get_queue, name="courses.views.ajax_get_queue"),
]

anytask/tasks/urls.py
import tasks.views
from django.conf.urls import url

urlpatterns = [
    url(r'^create/(?P<course_id>\d+)$', tasks.views.task_create_page,
        name="tasks.views.task_create_page"),
    url(r'^import/(?P<course_id>\d+)$', tasks.views.task_import_page,
        name="tasks.views.task_import_page"),
    url(r'^contest_import/(?P<course_id>\d+)$', tasks.views.contest_import_page,
        name="tasks.views.contest_import_page"),
    url(r'^edit/(?P<task_id>\d+)$', tasks.views.task_edit_page,
        name="tasks.views.task_edit_page"),
    url(r'^get_contest_problems', tasks.views.get_contest_problems,
        name="tasks.views.get_contest_problems"),
    url(r'^contest_task_import', tasks.views.contest_task_import,
        name="tasks.views.contest_task_import"),
    url(r'^popup/(?P<task_id>\d+)$', tasks.views.get_task_text_popup,
        name="tasks.views.get_task_text_popup"),
    url(r'^validate/nb_assignment_name', tasks.views.validate_nb_assignment_name,
        name="tasks.views.validate_nb_assignment_name"),
]

anytask/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.views.generic.base import TemplateView
import users.views
import django.contrib.auth.views
import django.views.static
import index.views
import admission.views

from middleware.lang_middleware import set_lang_view, get_lang_view

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^course/', include('courses.urls')),
    url(r'^issue/', include('issues.urls')),
    url(r'^school/', include('schools.urls')),
    url(r'^task/', include('tasks.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^users/(?P<username>.*)/', users.views.users_redirect),
    url(r'^setlanguage/', users.views.set_user_language),
    url(r'^invites/', include('invites.urls')),
    url(r'^anyrb/', include('anyrb.urls')),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, {'next_page': '/'}),
    url(r'^accounts/profile/(?P<username>.*)/(?P<year>\d+)', users.views.profile, name='users.views.profile'),
    url(r'^accounts/profile/(?P<username>.*)', users.views.profile, name='users.views.profile'),
    url(r'^accounts/profile', users.views.profile, name='users.views.profile'),
    url(r'^accounts/', include('registration.backends.default_with_names.urls')),
    url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^about$', TemplateView.as_view(template_name='about.html')),
    url(r'^$', index.views.index, name="index.views.index"),
    url(r'^archive/', index.views.archive_index, name="index.views.archive_index"),
    url(r'^search/', include('search.urls')),
    url(r'^staff', include('staff.urls')),
    url(r'^mail/', include('mail.urls')),
    url(r'^admission/', include('admission.urls')),
    url(r'^shad2017/register', admission.views.register),
    url(r'^shad2017/activate/(?P<activation_key>\w+)/', admission.views.activate),
    url(r'^shad2017/decline/(?P<activation_key>\w+)/', admission.views.decline),
    url(r'^lesson/', include('lessons.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^jupyter/', include('jupyter.urls')),
    url(r'^set_lang/', set_lang_view, name='set_lang'),
    url(r'^get_lang/', get_lang_view, name='get_lang'),
    url(r'^robots.txt$', index.views.robotstxt_view, name="index.views.robotstxt_view"),
]

anytask/users/forms.py
# coding: utf-8
from django import forms
from django.conf import settings
from django.utils.translation import ugettext as _
from invites.models import Invite
from django.utils import timezone

import datetime

attrs_dict = {'class': 'required'}


class InviteActivationForm(forms.Form):
    invite = forms.CharField(widget=forms.TextInput(attrs=attrs_dict), label="")

    def clean_invite(self):
        """
        Validate that the invite is not already
        in use and exists.
        """

        try:
            invite = Invite.objects.get(key=self.cleaned_data['invite'])
        except:  # noqa
            raise forms.ValidationError(_(u"invajta_ne_sushestvuet"))

        if invite.added_time + datetime.timedelta(days=settings.INVITE_EXPIRED_DAYS) < timezone.now():
            raise forms.ValidationError(_(u"srok_dejstvija_invajta_istek"))
        else:
            return self.cleaned_data['invite']

anytask/courses/views.py
# coding: utf-8

from django.shortcuts import render, get_object_or_404
from django.http import Http404, QueryDict
from django.core.exceptions import PermissionDenied
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth.models import User
from django.utils.translation import ugettext as _
from django.utils.timezone import localtime, now
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.views.decorators.http import require_http_methods

from collections import defaultdict, Counter, OrderedDict
import datetime
import logging
import requests
from reversion import revisions as reversion

from courses.models import Course, DefaultTeacher, StudentCourseMark, MarkField, FilenameExtension
from groups.models import Group
from tasks.models import Task, TaskGroupRelations
from years.models import Year
from years.common import get_current_year
from anycontest.common import get_contest_info, FakeResponse
from issues.models import Issue
from issues.issueFilter import IssueFilter
from issues.model_issue_status import IssueStatus
from issues.views import contest_rejudge
from users.forms import InviteActivationForm
from users.models import UserProfile
from courses import pythontask
from lessons.models import Lesson

from common.timezone import convert_datetime

from courses.forms import default_teacher_forms_factory, DefaultTeacherForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML
from functools import reduce

import json

logger = logging.getLogger('django.request')

QUEUE_SESSION_PREFIX = 'queue'
QUEUE_COLUMN_ORDER = {
    "1": ["student__last_name", "student__first_name"],
    "2": ["task__title"],
    "3": ["update_time"],
    "4": ["mark"],
    "5": ["responsible__last_name", "responsible__first_name"],
}


@require_http_methods(['GET'])
@login_required
def queue_page(request, course_id):
    user = request.user
    course = get_object_or_404(Course, id=course_id)

    if not course.user_can_see_queue(user):
        raise PermissionDenied

    f = IssueFilter(request.GET, {})
    f.set_course(course, user)
    session_key = '_'.join([QUEUE_SESSION_PREFIX, str(course_id)])
    if request.GET:
        request.session[session_key] = f.form.data
    elif session_key in request.session:
        f.form.data = request.session.get(session_key)
    f.form.helper = FormHelper(f.form)
    f.form.helper.form_method = 'get'
    f.form.helper.layout.append(
        HTML(
            u"""
            <div class="form-group row">
            <button id="button_clear" class="btn btn-secondary" type="button">{0}</button>
            </div>
            <div class="form-group row">
            <button id="button_filter" class="btn btn-primary" type="button">{1}</button>
            </div>
            """.format(_(u'ochistit'), _(u'primenit'))
        )
    )

    schools = course.school_set.all()

    context = {
        'course': course,
        'user_is_teacher': course.user_is_teacher(user),
        'visible_attendance_log': course.user_can_see_attendance_log(user),
        'filter': f,
        'school': schools[0] if schools else '',
        'full_width_page': True,
        'timezone': user.profile.time_zone
    }
    return render(request, 'courses/queue.html', context)


def set_order_direction(values, direction):
    if direction == "desc":
        return map(lambda x: "-" + x, values)
    return values


@require_http_methods(['POST'])
@login_required
def ajax_get_queue(request):
    user = request.user

    if "draw" not in request.POST or "course_id" not in request.POST:
        raise PermissionDenied

    course = get_object_or_404(Course, id=request.POST['course_id'])

    if not course.user_can_see_queue(user):
        raise PermissionDenied

    issues = Issue.objects.filter(
        Q(task__course=course)
        & (Q(student__profile__user_status__tag='active') | Q(student__profile__user_status__tag=None))
        & Q(student__group__course=course)
    ).exclude(
        task__type=Task.TYPE_SEMINAR,
    ).exclude(
        task__type=Task.TYPE_MATERIAL,
    ).distinct().select_related('student', 'task', 'responsible', 'status_field')

    order = []
    for order_info in json.loads(request.POST.get("order", "[]")):
        order.extend(set_order_direction(QUEUE_COLUMN_ORDER.get(str(order_info.get("column"))), order_info.get("dir")))
    issues = issues.order_by(*order)

    f = IssueFilter(QueryDict(request.POST["filter"]), issues)
    f.set_course(course, user)
    f.set_data(request.POST)
    session_key = '_'.join([QUEUE_SESSION_PREFIX, str(course.id)])
    if f.form.data:
        request.session[session_key] = f.form.data
    f.qs.count()

    return HttpResponse(json.dumps(f.response), content_type="application/json")


@require_http_methods(['GET'])
@login_required
def gradebook(request, course_id, task_id=None, group_id=None):
    """Page with course related information
    contexts:
        - tasklist
        - tasks_description
    """
    user = request.user

    if not user.profile.is_active():
        raise PermissionDenied

    course = get_object_or_404(Course, id=course_id)
    if task_id:
        task = get_object_or_404(Task, id=task_id, type=Task.TYPE_SEMINAR)
    else:
        task = None

    if group_id:
        group = get_object_or_404(Group, id=group_id)
    else:
        group = None

    schools = course.school_set.all()

    if course.private and not course.user_is_attended(request.user):
        return render(request, 'courses/course_forbidden.html',
                      {"course": course,
                       'school': schools[0] if schools else '',
                       'invite_form': InviteActivationForm()})
    lang = request.session.get('django_language', user.profile.language)
    issue_statuses = []
    seminar_color = IssueStatus.COLOR_DEFAULT
    for status in course.issue_status_system.statuses.all():
        issue_statuses.append((status.color, status.get_name(lang)))
        if status.tag == IssueStatus.STATUS_SEMINAR:
            seminar_color = status.color

    tasklist_context = tasklist_shad_cpp(request, course, task, group)

    context = tasklist_context
    context.update({
        'tasklist_template': 'courses/tasklist/shad_cpp.html',
        'task_types': dict(Task().TASK_TYPE_CHOICES).items(),
        'group_gradebook': True if group else False,
        'show_hidden_tasks': request.session.get(
            str(request.user.id) + '_' + str(course.id) + '_show_hidden_tasks', False
        ),
        'show_academ_users': request.session.get(
            str(request.user.id) + '_' + str(course.id) + '_show_academ_users', True
        ),
        'school': schools[0] if schools else '',
        'full_width_page': True,
        'issue_statuses': issue_statuses,
        'seminar_color': seminar_color,
    })

    return render(request, 'courses/gradebook.html', context)


@require_http_methods(['GET'])
@login_required
def course_page(request, course_id):
    """Page with course related information
    contexts:
        - tasklist
        - tasks_description
    """
    user = request.user
    if not user.profile.is_active():
        raise PermissionDenied

    course = get_object_or_404(Course, id=course_id)
    if course.is_python_task:
        return pythontask.tasks_list(request, course)

    schools = course.school_set.all()

    if course.private and not course.user_is_attended(request.user):
        return render(request, 'courses/course_forbidden.html',
                      {"course": course,
                       'school': schools[0] if schools else '',
                       'invite_form': InviteActivationForm()})
    course.can_edit = course.user_can_edit_course(user)
    if course.can_edit:
        groups = course.groups.all().order_by('name')
        tasks = [{'group': tgr.group, 'task': tgr.task} for tgr in
                 TaskGroupRelations.objects.filter(task__course=course, group__in=groups, deleted=False).order_by(
                     'group', 'position')]
    else:
        groups = Group.objects.filter(students=user, course__in=[course])
        tasks = TaskGroupRelations.objects.filter(
            task__course=course, group__in=groups, deleted=False
        ).order_by(
            'group', 'position'
        ).values_list(
            'task__id', flat=True
        ).distinct()
        tasks = Task.objects.filter(id__in=tasks)

    if StudentCourseMark.objects.filter(student=user, course=course):
        mark = StudentCourseMark.objects.get(student=user, course=course).mark
    else:
        mark = None

    context = {}

    context['course'] = course
    context['tasks'] = tasks
    context['mark'] = mark or '--'
    context['visible_queue'] = course.user_can_see_queue(user),
    context['visible_attendance_log'] = course.user_can_see_attendance_log(user),
    context['user_is_teacher'] = course.user_is_teacher(user)
    context['task_types'] = dict(Task().TASK_TYPE_CHOICES).items()
    context['show_hidden_tasks'] = request.session.get(
        str(request.user.id) + '_' + str(course.id) + '_show_hidden_tasks', False)
    context['school'] = schools[0] if schools else ''
    context['visible_attendance_log'] = course.user_can_see_attendance_log(request.user)
    context['jupyterhub_url'] = getattr(settings, 'JUPYTERHUB_URL', '')

    return render(request, 'courses/course.html', context)


@login_required
def seminar_page(request, course_id, task_id):
    """Page with course related information
    contexts:
        - tasklist
        - tasks_description
    """

    user = request.user
    if not user.profile.is_active():
        raise PermissionDenied

    course = get_object_or_404(Course, id=course_id)
    task = get_object_or_404(Task, id=task_id, type=Task.TYPE_SEMINAR)
    schools = course.school_set.all()

    if course.private and not course.user_is_attended(request.user):

anytask/courses/templates/courses/attendance.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap_breadcrumbs %}
{% load sanitize_html icon %}
{% load dict_func %}
{% load task_taken_func %}
<link href="{{ STATIC_URL }}shad_cpp.css" rel='stylesheet'/>

{% block title %}{{ course.name }} | {{ course.year }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% if school %}
        {% breadcrumb school.name school.get_absolute_url %}
    {% endif %}
    {% breadcrumb course.name course.get_absolute_url %}
    {% if group_attendance_list %}
        {% breadcrumb group_information|get_group_name "" %}
    {% else %}
        {% breadcrumb_for "" %}{% trans "zhurnal_poseshaemosti" %}{% endbreadcrumb_for %}
    {% endif %}
{% endblock breadcrumbs %}

{% block navbar %}
    <ul class="nav navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{{ course.get_absolute_url }}"> {% trans "stranica_kursa" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ course.get_absolute_url }}/gradebook/">{% trans "obshaja_vedomost" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if not group_attendance_list %}active{% endif %}"
               href="{{ course.get_absolute_url }}/attendance">{% trans "zhurnal_poseshaemosti" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{{ course.get_absolute_url }}/queue">{% trans "ochered_na_proverku" %}</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url "courses.views.course_settings" course.id %}">{% trans "nastrojki" %}</a>
        </li>
    </ul>
{% endblock navbar %}

{% block content %}
    {{ block.super }}
    <div id="legend">
         <div class="card card-block">
            <div class="row">
                <div class="col-md-12 col-xs-12">
                    <a type="button" class="btn btn-secondary btn-sm" href="/lesson/create/{{ course.id }}">
                        {% trans "dobavit_zaniatie" %}</a>
                    {% if visible_hide_button_users %}
                        <a class="btn btn-secondary btn-sm" id="hide_academ_student_btn">
                            {% if show_academ_users %}
                                {% trans "ne_pokazyvat_otchislennyh" %}
                            {% else %}
                                {% trans "pokazyvat_otchislennyh" %}
                            {% endif %}
                        </a>
                    {% endif %}
                </div>
            </div>
         </div>
    </div>

    {% include "courses/task.html" %}
    {% include lssnlist_template %}
{% endblock content %}

anytask/courses/templates/courses/attendance_list.html
{% load sanitize_html icon %}
{% load i18n %}
{% load dict_func %}
{% load task_taken_func %}
{% load tz %}

{% block scripts %}
    <link href="{{ STATIC_URL }}shad_cpp.css" rel='stylesheet'/>

    {% include "courses/course_js.html" %}
{% endblock scripts %}

{% for group, student_information in group_information.items %}
    <div class="card card-block {% if group_attendance_list %}group-table{% endif %}" for="#table_results_{{ group.id }}">
        <div class="row">
            <div class="col-md-6">
                <div class="card-title-block">
                    {% ifnotequal group course.group_with_extern %}
                        <h5 class="card-title">
                            {% if group.name %}{% if not group_attendance_list %}<a class="card-link table-link" href="{{ course.get_absolute_url }}/attendance/group/{{ group.id }}">{% endif %}{{ group.name }}</a>{% endif %}&nbsp;
                            {% if default_teacher|key:group %}
                                (<a class="card-link table-link" href="{{ default_teacher|get_url:group }}">{{ default_teacher|get_name:group }}</a>)
                            {% endif %}
                        </h5>
                    {% endifnotequal %}
                    {% if not group_attendance_list %}<button class="btn btn-secondary btn-table-fullscreen" type="button" for="#table_results_{{ group.id }}"><i class="fa fa-expand fa-lg"></i></button>{% endif %}
                </div>
            </div>
        </div>
        <div class="loading-table-img">
            <span class="fa fa-circle-o-notch fa-spin fa-3x fa-fw loading"></span>
        </div>
        <div class="zui-wrapper collapse">
            <table class="table table-striped table-bordered table-results order-column hover" cellspacing="0"  id="table_results_{{ group.id }}">
                <thead>
                <tr>
                    <th class="no-font-weight text-center">#</th>
                    <th class="no-font-weight"><b>{% trans "student" %}</b></th>
                    {% for lssn in group_lessons|key:group %}
                            <th align="center" class="dom-checked word-wrap" id="column_{{lssn.id}}">
                                <a href="javascript:get_lesson_modal('{{group.id}}', '{{lssn.id}}', '{{lssn.title|escapejs}}', '{% localtime on %}{{lssn.date_starttime|date:'d-m-Y H:i'}}{% endlocaltime %}',
                                '{% localtime on %}{{lssn.date_endtime|date:'d-m-Y H:i'}}{% endlocaltime %}', '{{lssn.description|safe|escapejs}}')" data-deleted='{{ lssn|lssn_can_be_deleted }}' {% if lssn.title %}data-toggle="popover-short-title" data-trigger="hover" data-placement="bottom" data-content="{{lssn.title}} "{% endif %}>
                                    {% localtime on %}{{lssn.date_starttime|date:'d-m-Y'}}{% endlocaltime %}
                                </a>
                            </th>
                        {% empty %}
                    {% endfor %}
                    <th align="center" class="no-font-weight dom-number">
                        {% trans "poseshennye_uroki" %} <span class="label label-inverse" id="total_lessons_{{ group.id }}">{{ group_lessons|key:group|length }}</span>
                    </th>
                </tr>
                </thead>
                <tbody>
                {% for student, not_visited_lessons, visited_lessons in student_information %}
                    <tr class="{% if user.username == student.username %}table-info{% endif %}">
                        <td class="sticky-col" align="center"></td>
                        <td class="sticky-col">
                            {% if not student.profile.is_active  %}<del>{% endif %}
                            <a class="card-link table-link" href="{{ student.get_absolute_url }}">{{ student.last_name }}&nbsp;{{ student.first_name }}</a>
                            {% if not student.profile.is_active  %}</del>{% endif %}
                        </td>
                        {% for lssn in group_lessons|key:group %}
                            <td align="center" class="student_{{ student.id }}">
                                <form method="post" class="lesson-visited-form">
                                    {% csrf_token %}
                                    <input type="hidden" name="lssn_id" value="{{lssn.id}}"/>
                                    <input type="hidden" name="student_id" value="{{student.id}}"/>
                                    <input type="hidden" name="group_id" value="{{group.id}}"/>
                                    <div class="checkbox-success">
                                        <input type="checkbox" name="lesson_visited" id="checklesson_{{lssn.id}}_{{student.id}}"
                                               {% if lssn in group_inactive_lessons|key:group %}class="checkbox-success notactive" disabled
                                               {% else %}class="checkbox-success" {%if lssn not in not_visited_lessons %}checked{% endif %}{% endif %}>
                                        <label for="checklesson_{{lssn.id}}_{{student.id}}"></label>
                                    </div>
                                </form>
                            </td>
                            {% empty %}
                        {% endfor %}
                        <td align="center" class="total-lessons">
                            <div>
                                <span class="label label-inverse" id="total-lessons_{{group.id}}_{{student.id}}">{{ visited_lessons }}</span>
                            </div>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endfor %}

anytask/courses/templates/courses/course_forbidden.html
{% extends "base.html" %}
{% load i18n %}
{% load django_bootstrap_breadcrumbs %}
{% load crispy_forms_tags %}

{% block title %}{{ course.name }} | {{ course.year }}{% endblock %}

{% block scripts %}
    <script src="{{ STATIC_URL }}jquery.validate.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#invites_form').validate({
                submitHandler: function(form) {
                    $('#invites_form').ajaxSubmit({
                        success: function (data) {
                            if (data.is_error) {
                                $('#id_invite').removeClass('form-control-success').addClass('form-control-danger')
                                        .closest('.form-group').removeClass('has-success').addClass('has-danger');
                                $('#id_invite').siblings('small.text-help').empty().append(data.invite);
                            }
                            else {
                                $('#id_invite').removeClass('form-control-danger').addClass('form-control-success')
                                        .closest('.form-group').removeClass('has-danger').addClass('has-success');
                                window.location.reload();
                            }
                        },
                        error: function (data) {
                            $('#id_invite').removeClass('form-control-success').addClass('form-control-danger')
                                    .closest('.form-group').removeClass('has-success').addClass('has-danger');
                            $('#id_invite').siblings('small.text-help').empty().append('{% trans "oshibka" %}: '+ data.status);
                        }
                    });
                },
                rules: {
                    invite: {
                        required : true
                    }
                },

                highlight: function(input) {
                    $(input).removeClass('form-control-success').addClass('form-control-danger');
                    $(input).closest('.form-group').removeClass('has-success').addClass('has-danger');
                },

                success: function(label) {
                    label.addClass('valid');
                    label.closest('.text-help').siblings('.form-control').removeClass('form-control-danger');
                    label.closest('.form-group').removeClass('has-danger');
                },

                messages: {
                    invite: {
                        required : "{% trans "ukazat_invajt" %}"
                    }
                },

                errorPlacement: function(error, element) {
                    $(element).siblings('small.text-help').empty().append(error);
                }
            });
        });
    </script>
{% endblock scripts %}

{% block breadcrumbs %}
    {{ block.super }}
    {% if school %}
        {% breadcrumb school.name school.get_absolute_url %}
    {% endif %}
    {% breadcrumb course.name "" %}
{% endblock breadcrumbs %}

{% block content %}
    {{ block.super }}

    <div class="row">
        <div class="col-md-6 col-sm-12">
            <div class="card card-block">
                <h5 class="card-title">{% trans "dostup_ogranichen" %}</h5>
                <p class="card-text">{% trans "vvedite_invajt" %}</p>
                <form id="invites_form" action="{% url "users.views.activate_invite" %}" method="post">
                    <div class="row">
                        {% csrf_token %}
                        <input type="hidden" name="course_id" value="{{ course.id }}">
                        {% for field in invite_form %}
                            <div class="form-group col-md-9" style="height: 3rem">
                                <div class="controls">
                                    <input class="form-control" id='{{ field.id_for_label }}' name='{{ field.html_name }}' type='text' placeholder="{% trans "vvedite_invajt" %}">
                                    <small class="text-help" id="{{ field.id_for_label }}_error_text">&nbsp;</small>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="col-md-3">
                            <button type="submit" class="btn btn-secondary">OK</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

anytask/courses/templates/courses/tasks_description.html
{% load sanitize_html %}
{% load i18n %}

<h1>
  tasks_description
</h1>

<div class="row span8">
  {% for group,tasks in group_x_tasks.items %}
  <h2>{{ group.name }}</h2>
  <dl>
    {% for task in tasks %}
    <dt>{{ task.title }}</dt>
    <dd>{{ task.task_text|sanitize|safe }}</dd>
    <br>
    {% endfor %}
  </dl>
  {% endfor %}
  {% if course_tasks %}
  <h2>{% trans "zadachi_kursa" %}</h2>
  <dl>
    {% for task in course_tasks %}
    <dt>{{ task.title }}</dt>
    <dd>{{ task.task_text|sanitize|safe }}</dd>
    <br>
    {% endfor %}
  </dl>
  {% endif %}
</div>