anytask/issues/urls.py
from django.conf.urls import url

import issues.views as views

urlpatterns = [
    url(r'^(?P<issue_id>\d+)$', views.issue_page, name="issues.views.issue_page"),
    url(r'^get_or_create/(?P<task_id>\d+)/(?P<student_id>\d+)$', views.get_or_create,
        name="issues.views.get_or_create"),
    url(r'^upload/$', views.upload, name='jfu_upload'),
    url(r'^delete/(?P<pk>\d+)$', views.upload_delete, name='jfu_delete'),
]

anytask/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.views.generic.base import TemplateView
import users.views
import django.contrib.auth.views
import django.views.static
import index.views
import admission.views

from middleware.lang_middleware import set_lang_view, get_lang_view

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^course/', include('courses.urls')),
    url(r'^issue/', include('issues.urls')),
    url(r'^school/', include('schools.urls')),
    url(r'^task/', include('tasks.urls')),
    url(r'^user/', include('users.urls')),
    url(r'^users/(?P<username>.*)/', users.views.users_redirect),
    url(r'^setlanguage/', users.views.set_user_language),
    url(r'^invites/', include('invites.urls')),
    url(r'^anyrb/', include('anyrb.urls')),
    url(r'^accounts/logout/$', django.contrib.auth.views.logout, {'next_page': '/'}),
    url(r'^accounts/profile/(?P<username>.*)/(?P<year>\d+)', users.views.profile, name='users.views.profile'),
    url(r'^accounts/profile/(?P<username>.*)', users.views.profile, name='users.views.profile'),
    url(r'^accounts/profile', users.views.profile, name='users.views.profile'),
    url(r'^accounts/', include('registration.backends.default_with_names.urls')),
    url(r'^static/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', django.views.static.serve, {'document_root': settings.MEDIA_ROOT}),
    url(r'^about$', TemplateView.as_view(template_name='about.html')),
    url(r'^$', index.views.index, name="index.views.index"),
    url(r'^archive/', index.views.archive_index, name="index.views.archive_index"),
    url(r'^search/', include('search.urls')),
    url(r'^staff', include('staff.urls')),
    url(r'^mail/', include('mail.urls')),
    url(r'^admission/', include('admission.urls')),
    url(r'^shad2017/register', admission.views.register),
    url(r'^shad2017/activate/(?P<activation_key>\w+)/', admission.views.activate),
    url(r'^shad2017/decline/(?P<activation_key>\w+)/', admission.views.decline),
    url(r'^lesson/', include('lessons.urls')),
    url(r'^api/', include('api.urls')),
    url(r'^jupyter/', include('jupyter.urls')),
    url(r'^set_lang/', set_lang_view, name='set_lang'),
    url(r'^get_lang/', get_lang_view, name='get_lang'),
    url(r'^robots.txt$', index.views.robotstxt_view, name="index.views.robotstxt_view"),
]

anytask/issues/models.py
# coding: utf-8

import os
import uuid
from decimal import Decimal

from anyrb.common import AnyRB
from anyrb.common import update_status_review_request
from django.conf import settings
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from django.db.models import Q
from django.dispatch import receiver
from django.utils import timezone
from django.utils.translation import ugettext as _
from issues.model_issue_field import IssueField
from issues.model_issue_status import IssueStatus
from tasks.models import Task
from text_unidecode import unidecode
from users.common import get_user_fullname, get_user_link


def get_file_path(instance, filename):
    return '/'.join(['files', str(uuid.uuid4()), filename])


def normalize_decimal(number):
    new_number = Decimal(str(number))
    new_number = new_number.normalize()
    exponent = new_number.as_tuple()[2]
    if exponent > 10:
        new_number = Decimal(0)
    elif exponent > 0:
        new_number = new_number.quantize(1)

    return new_number


class File(models.Model):
    file = models.FileField(upload_to=get_file_path, null=True, blank=True, max_length=500)
    event = models.ForeignKey("Event", on_delete=models.DO_NOTHING)
    deleted = models.BooleanField(default=False)

    def filename(self):
        return os.path.basename(self.file.name)


class Issue(models.Model):
    student = models.ForeignKey(
        User,
        db_index=True,
        null=False,
        blank=False,
        related_name="student",
        on_delete=models.DO_NOTHING,
    )
    costudents = models.ManyToManyField(User, blank=True, db_index=True, related_name='costudents')

    task = models.ForeignKey(
        Task, db_index=True, null=True, blank=False, on_delete=models.DO_NOTHING
    )

    mark = models.FloatField(db_index=False, null=False, blank=False, default=0)

    create_time = models.DateTimeField(auto_now_add=True)  # remove default=timezone.now
    update_time = models.DateTimeField(default=timezone.now)

    responsible = models.ForeignKey(
        User,
        db_index=True,
        null=True,
        blank=True,
        related_name="responsible",
        on_delete=models.DO_NOTHING,
    )
    followers = models.ManyToManyField(User, blank=True)

    STATUS_NEW = 'new'
    STATUS_AUTO_VERIFICATION = 'auto_verification'
    STATUS_NEED_INFO = 'need_info'
    HIDDEN_STATUSES = {STATUS_NEW: 1,
                       STATUS_AUTO_VERIFICATION: 2,
                       STATUS_NEED_INFO: 6}

    STATUS_REWORK = IssueStatus.STATUS_REWORK
    STATUS_VERIFICATION = IssueStatus.STATUS_VERIFICATION
    STATUS_ACCEPTED = IssueStatus.STATUS_ACCEPTED

    ISSUE_STATUSES = (
        (STATUS_NEW, _(u'novyj')),
        (STATUS_REWORK, _(u'na_dorabotke')),
        (STATUS_VERIFICATION, _(u'na_proverke')),
        (STATUS_ACCEPTED, _(u'zachteno')),
        (STATUS_AUTO_VERIFICATION, _(u'na_avtomaticheskoj_proverke')),
        (STATUS_NEED_INFO, _(u'trebuetsja_informacija')),
    )

    status = models.CharField(max_length=20, choices=ISSUE_STATUSES, default=STATUS_NEW)
    status_field = models.ForeignKey(
        IssueStatus,
        db_index=True,
        null=False,
        blank=False,
        default=1,
        on_delete=models.DO_NOTHING,
    )

    def is_status_accepted(self):
        return self.status_field.tag in [IssueStatus.STATUS_ACCEPTED, IssueStatus.STATUS_ACCEPTED_AFTER_DEADLINE]

    def is_status_only_accepted(self):
        return self.status_field.tag == IssueStatus.STATUS_ACCEPTED

    def is_status_accepted_after_deadline(self):
        return self.status_field.tag == IssueStatus.STATUS_ACCEPTED_AFTER_DEADLINE

    def is_status_auto_verification(self):
        return self.status_field.tag == IssueStatus.STATUS_AUTO_VERIFICATION

    def is_status_new(self):
        return self.status_field.tag == IssueStatus.STATUS_NEW

    def is_status_rework(self):
        return self.status_field.tag == IssueStatus.STATUS_REWORK

    def is_status_need_info(self):
        return self.status_field.tag == IssueStatus.STATUS_NEED_INFO

    def is_status_verification(self):
        return self.status_field.tag == IssueStatus.STATUS_VERIFICATION

    def score(self):
        field = IssueField.objects.get(id=8)

        mark = self.get_field_value(field)
        if mark:
            mark = normalize_decimal(mark)
        else:
            mark = 0
        return mark

    def last_comment(self):
        field = IssueField.objects.get(id=1)
        comment = self.get_field_value(field)
        if not comment:
            comment = ''

        return comment

    def get_field_repr(self, field, lang=settings.LANGUAGE_CODE):
        name = field.name

        if name == 'student_name':
            return get_user_link(self.student)
        if name == 'responsible_name':
            if self.responsible:
                return get_user_link(self.responsible)
            return None
        if name == 'followers_names':
            followers = map(
                lambda x: u'<a class="user" href="{0}">{1}</a>'.format(
                    x.get_absolute_url(), get_user_fullname(x)
                ),
                self.followers.all()
            )
            return ', '.join(followers)
        if name == 'costudents_names':
            costudents = map(
                lambda x: u'<a class="user" href="{0}">{1}</a>'.format(
                    x.get_absolute_url(), get_user_fullname(x)
                ),
                self.costudents.all()
            )
            return ', '.join(costudents)
        if name == 'course_name':
            course = self.task.course
            return u'<a href="{0}">{1}</a>'.format(course.get_absolute_url(), course.name)
        if name == 'task_name':
            task = self.task
            return task.get_title(lang)
        if name == 'comment':
            return None
        if name == 'status':
            return self.status_field.get_name(lang)
        if name == 'mark':
            return self.score()
        if name == 'review_id' and self.task.rb_integrated:
            return u'<a href="{1}/r/{0}">{0}</a>'.format(
                self.get_byname('review_id'),
                settings.RB_API_URL,
            )
        if name == 'run_id' and self.task.contest_integrated:
            return u'<a href="https://contest.yandex.ru/contest/{1}/run-report/{0}">{0}</a>'.format(
                self.get_byname('run_id'),
                self.task.contest_id,
            )

        return self.get_field_value(field)

    def get_byname(self, name):
        field = IssueField.objects.get(name=name)
        return self.get_field_value(field)

    def get_field_value(self, field):
        name = field.name
        if name == 'student_name':
            return self.student
        if name == 'responsible_name':
            if self.responsible:
                return self.responsible
            return None
        if name == 'followers_names':
            ret = []
            for user in self.followers.all():
                ret.append(user.id)
            return ret
        if name == 'costudents_names':
            ret = []
            for user in self.costudents.all():
                ret.append(user.id)
            return ret
        if name == 'course_name':
            return self.task.course
        if name == 'task_name':
            return self.task
        if name == 'status':
            return self.status_field
        if name == 'max_mark':
            return self.task.score_max
        if name == 'mark':
            return self.mark

        events = Event.objects.filter(issue_id=self.id, field_id=field.id).order_by('-timestamp')[:1]
        if not events:
            fields_count = self.task.course.issue_fields.filter(id=field.id).count()
            if fields_count:
                self.set_field(field, field.get_default_value())
                if field.get_default_value() is not None:
                    return field.get_default_value()
                return ''
            else:
                raise AttributeError('field_name = {0}'.format(name))

        return events[0].value

    def get_field_value_for_form(self, field):
        ret = self.get_field_value(field)
        if field.name == 'responsible_name':
            if ret:
                ret = ret.id  # Hack hack hack :\
            return ret
        if field.name == 'status':
            if ret.id not in IssueStatus.HIDDEN_STATUSES.values():
                ret = ret.id
            else:
                ret = None
            return ret
        return ret

    def create_event(self, field, author):
        event = Event()
        event.issue = self
        event.field = field
        event.author = author
        event.save()

        return event

    def set_status_by_id(self, status_id, author=None):
        if int(status_id) in IssueStatus.HIDDEN_STATUSES.values():
            return self.set_byname('status', IssueStatus.objects.get(id=status_id))
        else:
            status = self.task.course.issue_status_system.statuses.filter(id=status_id)
            if status:
                return self.set_byname('status', status[0], author)

    def set_status_by_tag(self, tag, author=None):
        if tag in IssueStatus.HIDDEN_STATUSES:
            return self.set_byname('status', IssueStatus.objects.get(id=IssueStatus.HIDDEN_STATUSES[tag]))
        else:
            status = self.task.course.issue_status_system.statuses.filter(tag=tag)
            if status:
                return self.set_byname('status', status[0], author)
        return

    def set_status_accepted(self, author=None):
        self.set_status_by_tag(IssueStatus.STATUS_ACCEPTED, author)

    def set_status_new(self, author=None):
        self.set_status_by_tag(IssueStatus.STATUS_NEW, author)

    def set_status_accepted_after_deadline(self, author=None):
        self.set_status_by_tag(IssueStatus.STATUS_ACCEPTED_AFTER_DEADLINE, author)

anytask/issues/templates/issues/history.html
{% load link_to_open %}
{% load i18n %}
{% load tz %}
{% load info %}
{% get_current_language as LANGUAGE_CODE %}

{% load sanitize_html %}

<script type="text/javascript">

    $(document).on("click", "#old_comments_button", function() {
        if($("#top_alert").hasClass("clicked")) {
            $("#top_alert").show();
            $("#top_alert").removeClass("clicked");
        } else {
            $("#top_alert").hide();
            $("#top_alert").addClass("clicked");
        }
    });

</script>

<style>
    .mce-tinymce {
        margin-bottom: 1rem;
    }
    .ipynb-file-link .dropdown-menu{
        min-width: auto;
    }
</style>
<div class="card card-block">
    <h5 class="card-title">{% get_text_from_json issue.task 'get_title' LANGUAGE_CODE %}
        <a class="btn btn-secondary btn-sm btn-square btn-history-task-text" data-toggle="collapse" href="#task-text"
           aria-expanded="false" aria-controls="task-text">
            <span class="fa fa-caret-down"></span>
        </a>
    </h5>
    <div class="collapse" id="task-text">
        {{ issue.task|get_description:LANGUAGE_CODE|safe }}
    </div>
    {% if issue.task.type == issue.task.TYPE_IPYNB %}
    {% if user.profile.ya_passport_login %}
    <div>
{% blocktrans with jupyterhub_url_t=jupyterhub_url assignment_name_t=issue.task.nb_assignment_name %}
<p>For solving the task you need to go to <a href="{{ jupyterhub_url_t }}" target="_blank">JupyterHub</a>.</p>
<p>Open Assignments tab and fetch the '{{ assignment_name_t }}'</p>
{% endblocktrans %}
    </div>
    {% else %}
    <div class="alert alert-danger">
{% blocktrans with settings_url="/user/settings" %}
<p>Before solving this task you need to add your Yandex.Passport account.</p>
<p>In User Menu go to <a href="{{ settings_url }}">Settings</a> and authorize via Yandex</p>
{% endblocktrans %}
    </div>
    {% endif %}
    {% endif %}
</div>
<div class="card card-block">
    <h5 class="card-title">{% trans "obsuzhdenie_zadachi" %}</h5>
    <ul class="history">
        {% if issue.get_history.count > events_to_show %}
            <li>
                <button id="old_comments_button" type="button" class="btn btn-secondary" data-toggle="collapse" data-target="#old_comments">
                    {% trans "predydushie_soobshenija" %}
                </button>
            </li>
            {% if issue.update_time > issue.task.deadline_time and show_top_alert %}
                <li>
                    <div id="top_alert" class="alert alert-danger">
                        <strong>{% trans "srok_sdachi_istek" %}</strong> {% trans "soobshenija_budut_vydeljatsja" %}
                    </div>
                </li>
            {% endif %}
            <div id="old_comments" class="collapse">
        {% endif %}
        {% for event in issue.get_history %}
            {% if event.id == first_event_after_deadline.id %}
                <li>
                    <div id="event_alert" class="alert alert-danger">
                        <strong>{% trans "srok_sdachi_istek" %}</strong> {% trans "soobshenija_budut_vydeljatsja" %}
                    </div>
                </li>
            {% endif %}

            <li>
                <div class="row">
                    <div class="{% if event.author == user %}col-xs-12{% else %}col-xs-offset-1 col-xs-11{% endif %}">
                        <strong><a class="card-link" {% if event.author.username != "anytask" %}href="{{ event.author.get_absolute_url }}"{% endif %} style="color:#373a3c;">
                            {{ event.author.last_name }} {{ event.author.first_name }}</a>&nbsp;</strong>
                        <small class="text-muted">
                            <i class="fa fa-clock-o fa-flip-horizontal"></i>{% localtime on %} {{ event.timestamp|date:"d M H:i" }} {% endlocaltime %}
                        </small>
                    </div>
                    <div class="user_img col-xs-1 {% if event.author == user %}pull-xs-right{% else %}pull-xs-left{% endif %}">
                        <a class="card-link" {% if event.author.username != "anytask" %}href="{{ event.author.get_absolute_url }}"{% endif %}>
                            <img class="avatar" src="{% if not event.author.profile.avatar %}https://www.gravatar.com/avatar/00000000000000000000000000000000?d=mm&f=y
                        {% else %}{{ event.author.profile.avatar.url }}{% endif %}" style="width: 50px; height: 50px;">
                        </a>
                        {#                        <i class="fa {% if event.author == user %}fa-empire{% else %}fa-rebel{% endif %} fa-3x" aria-hidden="true"></i>#}
                    </div>
                    <div class="col-xs-11">
                        <div class="{% if event.author == user %}mine{% else %}not_mine{% endif %} history-body
                        {% if issue.task.deadline_time < event.timestamp and event.author.username == issue.student.username %}
                        after_deadline {% endif %}">
                            {% autoescape off %}
                                {{ event.get_message|sanitize }}
                            {% endautoescape %}
                            {% if event.file_set.all %}
                                <div class="files">
                                    <i class="fa fa-file-o"></i>
                                    {% for file in event.file_set.all %}
                                        {% with file_path=file.file.url %}
                                            {% if teacher_or_staff and file_path|is_ipynb %}
                                                <div class="btn-group ipynb-file-link">
                                                    <a class="dropdown-toggle" href="{% link_to_open file_path teacher_or_staff %}" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                        {{ file.filename }}
                                                    </a>
                                                    <div class="dropdown-menu dropdown-menu-right">
                                                        <a class="dropdown-item" href="{% link_to_open file_path teacher_or_staff %}" target="_blank">{% trans "otkryt" %}</a>
                                                        <a class="dropdown-item" href="{{ file_path }}">{% trans "skachat" %}</a>
                                                    </div>
                                                </div>
                                            {% else %}
                                                <a href="{% link_to_open file_path teacher_or_staff %}">{{ file.filename }}</a><br/>
                                            {% endif %}
                                        {% endwith %}
                                    {% endfor %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </li>
            {% if event.is_omg %}
                <li class="change">
                    {{ event.field.title }} changed to {{ event.value }} by {{ event.author.last_name }} {{ event.author.first_name }}
                </li>
            {% endif %}


            {% if forloop.revcounter0 == events_to_show %}
                </div>
            {% endif %}


        {% endfor %}
        {% if not issue.get_history %}
            {% trans "zdes_nichego_net" %}
        {% endif %}
    </ul>
</div>

<div>
    {% load jfutags %}
    {% jfu 'file_uploader.html' 'jfu_upload' %}
</div>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}typeahead.bundle.min.js"></script>

anytask/issues/templates/issues/issue_js.html
<script src="{{ STATIC_URL }}jquery.validate.min.js"></script>
{% load i18n %}
{# <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script> #}
{# <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/additional-methods.min.js"></script> #}
<script src="https://malsup.github.io/jquery.form.js"></script>
<script src="{{ STATIC_URL }}tinymce/tinymce.min.js"></script>
<script src="{{ STATIC_URL }}tinymce/jquery.tinymce.min.js"></script>
<script src="{{ STATIC_URL }}prism.js"></script>

<link href="{{ STATIC_URL }}prism.css" rel='stylesheet' />
<link href="{{ STATIC_URL }}tinymce-style-issue-comment.css" rel='stylesheet' />
<link href="{{ STATIC_URL }}tinymce-style-task.css" rel='stylesheet' />

<script type="text/javascript">
    var tinymce_default = {
        language: '{{ user.profile.language }}',
        skin: 'bootstrap4',
        content_css: [
            'https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css',
            '{{ STATIC_URL }}tinymce-style-issue-comment.css',
            '{{ STATIC_URL }}prism.css'
        ],
        relative_urls : false,
        remove_script_host: false
    };

    $(document).ready(function () {

        $(document).on('focusin', function(e) {
            if ($(e.target).closest(".mce-window").length) {
                e.stopImmediatePropagation();
            }
        });

        $('#task-text').on('hide.bs.collapse', function () {
            $(".btn-history-task-text").blur();
            window.sessionStorage.setItem('collapsed', true);
        }).on('show.bs.collapse', function () {
            $(".btn-history-task-text").blur();
            window.sessionStorage.setItem('collapsed', false);
        }).on('hidden.bs.collapse', function () {
            $("span.fa", ".btn-history-task-text").removeClass("fa-caret-up").addClass("fa-caret-down");
        }).on('shown.bs.collapse', function () {
            window.sessionStorage.setItem('collapsed', false);
            $("span.fa", ".btn-history-task-text").removeClass("fa-caret-down").addClass("fa-caret-up");
        });

        if(window.sessionStorage.getItem('collapsed') === "true") {
            $('#task-text').collapse('hide');
            $("span.fa", ".btn-history-task-text").removeClass("fa-caret-up").addClass("fa-caret-down");
        } else {
            $('#task-text').collapse('show');
            $("span.fa", ".btn-history-task-text").removeClass("fa-caret-down").addClass("fa-caret-up");
        }

        $("select[multiple]").multiselect({
            buttonClass: 'btn btn-secondary btn-block',
            templates: {
                ul: '<ul class="multiselect-container dropdown-menu" style="left:inherit;top: inherit;"></ul>',
                li: '<li><a tabindex="0" class="dropdown-item"><label></label></a></li>',
                filter: '<li class="multiselect-item filter"><div class="input-group"><input class="form-control multiselect-search" type="text"></div></li>',
                filterClearBtn: '<span class="input-group-btn"><button class="btn btn-secondary btn-block multiselect-clear-filter" type="button"><i class="fa fa-times"></i></button></span>'
            },
            enableCaseInsensitiveFiltering: true,
            filterPlaceholder: "{% trans "najti" %}",
            maxHeight: 200,
            buttonContainer: '<div style="width:100%;" class="multiselect-dropdown"/>',
            buttonWidth: '100%',
            buttonTitle: function(options, select) {
                var labels = [];

                if (options.length === 0) {
                    return '---';
                }
                else {
                    options.each(function () {
                        labels.push($(this).text());
                    });
                }
                return labels.join(', ');
            },
            buttonText: function(options, select) {
                if (options.length === 0) {
                    return '---';
                }
                else {
                    var labels = [];
                    options.each(function() {
                        if ($(this).attr('label') !== undefined) {
                            labels.push($(this).attr('label'));
                        }
                        else {
                            labels.push($(this).text());
                        }
                    });
                    return labels.join(', ') + '';
                }
            }
        });

        var info_width = $('ul.history').closest('.card').innerWidth();

        $("#id_comment").tinymce($.extend({}, tinymce_default, {
            setup: function(editor) {
                editor.addButton('preview_text', {
                    icon: false,
                    text: 'Preview',
                    cmd: 'mcePreview'
                });
                editor.addMenuItem('codesample', {
                    icon: 'codesample',
                    text: 'Insert/Edit code sample',
                    cmd: 'codesample'
                });
            },
            plugins: [
                'autoresize autosave autolink codesample hr image link lists',
                'table textpattern wordcount contextmenu preview paste'
            ],
            menubar: false,
            toolbar: 'undo redo | bold italic underline | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | image link hr | blockquote codesample table | preview_text',
            autoresize_bottom_margin: 10,
            autoresize_overflow_padding: 10,
            image_description: false,
            link_assume_external_targets: true,
            default_link_target: "_blank",
            target_list: false,
            link_title: false,
            table_default_attributes: {
                "class": 'table table-bordered table-comment'
            },
            textpattern_patterns: [
                {start: '1. ', cmd: 'InsertOrderedList'}
            ],
            contextmenu: "link image codesample",
            paste_auto_cleanup_on_paste : true,
            paste_remove_styles: true,
            paste_remove_styles_if_webkit: true,
            paste_strip_class_attributes: true,
            plugin_preview_width: info_width,
            autosave_ask_before_unload: false
        }));

        $("textarea.comment-verdict").tinymce($.extend({}, tinymce_default, {
            plugins: [
                'autolink lists paste placeholder'
            ],
            content_style: "body {padding: .375rem .75rem;}",
            height: 40,
            menubar: false,
            toolbar: false,
            statusbar: false,
            default_link_target: "_blank",
            autosave_ask_before_unload: false
        }));

        $("#id_comment").keydown(function (e) {
            if (e.ctrlKey && e.keyCode == 13) {
                $("form#comment").submit();
            }
        });

        $('div.container form:not(.navbar-form)').submit(function(e){
            var d = 'disabled';
            if ($(this).valid()) {
                $(this).find('button[type="submit"]:first').attr(d, d).prop(d, true).html("<span class='fa fa-circle-o-notch fa-spin fa-fw'></span> {% trans "sohranenie" %}");
                $(this).find('button[type="submit"]:not(:first)').hide();
                $(this).find('.dropdown-submit').hide();
            }
        });

        $('#modal_task_description_btn').click(function (e) {
            $('#modal_task_description').modal('show');
            e.preventDefault();
        });

        jQuery.validator.addMethod("lt_max", function(value, element) {
            var value = parseFloat(value);
            var max = parseFloat($('#max_mark').val());
            return isNaN(value) || value <= max;
        });

        $("#mark_form").validate({
            rules: {
                mark: {
                    required : true,
                    number: true,
                    min: 0,
                    lt_max: true
                }
            },

            highlight: function(input) {
                $(input).removeClass('form-control-success').addClass('form-control-danger');
                $('#mark_fieldset_id').removeClass('has-success').addClass('has-danger');
            },

            success: function(label) {
                label.addClass('valid');
                $('#id_mark').removeClass('form-control-danger').addClass('form-control-success');
                $('#mark_fieldset_id').removeClass('has-danger').addClass('has-success');
            },

            messages: {
                mark: {
                    required : "{% trans "neobhodimo_ukazat_ocenku" %}",
                    number : "{% trans "naturalnoe_chislo" %}",
                    min : "{% trans "ocenka_bolshe_ili_ravna_0" %}",
                    lt_max : "{% trans "ocenka_ne_bolshe" %} " + $('#max_mark').val()
                }
            },

            errorPlacement: function (error, element) {
                $('#mark_edit_error_text').empty().append(error );
            }
        });
    });

    function add_file_field() {
        var files = $('#id_files')[0].outerHTML;
        $("#file_field").append('<tr><td>' + files + '</td></tr>');
    }


</script>